BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "orderDetail" (
	"id"	INTEGER NOT NULL,
	"orderID"	INTEGER NOT NULL,
	"productQuantity"	INTEGER DEFAULT 1,
	"productID"	INTEGER,
	"tax"	REAL,
	"price"	REAL NOT NULL,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "order" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"userID"	INTEGER NOT NULL,
	"address"	VARCHAR NOT NULL,
	"date"	TIMESTAMP NOT NULL,
	"shipped"	BOOLEAN NOT NULL DEFAULT 'False'
);
CREATE TABLE IF NOT EXISTS "user" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"email"	VARCHAR NOT NULL,
	"firstName"	VARCHAR,
	"lastName"	VARCHAR,
	"address"	VARCHAR
);
CREATE TABLE IF NOT EXISTS "category" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"name"	VARCHAR NOT NULL
);
CREATE TABLE IF NOT EXISTS "product" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"name"	VARCHAR NOT NULL,
	"description"	TEXT,
	"productCategory"	INTEGER,
	"price"	REAL NOT NULL
);
COMMIT;
