BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "orderDetail" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"orderID"	INTEGER NOT NULL,
	"productQuantity"	INTEGER DEFAULT 1,
	"productID"	INTEGER NOT NULL,
	"tax"	REAL,
	"price"	INTEGER NOT NULL,
	FOREIGN KEY("productID") REFERENCES "product"("id"),
	FOREIGN KEY("orderID") REFERENCES "order"("id")
);
CREATE TABLE IF NOT EXISTS "order" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"userID"	INTEGER,
	"address"	INTEGER,
	"date"	NUMERIC,
	"shipped"	NUMERIC NOT NULL DEFAULT 0,
	FOREIGN KEY("userID") REFERENCES "user"("id")
);
CREATE TABLE IF NOT EXISTS "user" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"email"	TEXT NOT NULL,
	"firstname"	TEXT,
	"lastname"	TEXT,
	"address"	TEXT
);
CREATE TABLE IF NOT EXISTS "product" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"name"	TEXT NOT NULL,
	"description"	TEXT,
	"category"	INTEGER NOT NULL,
	"price"	REAL NOT NULL,
	FOREIGN KEY("category") REFERENCES "category"("id")
);
CREATE TABLE IF NOT EXISTS "category" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"name"	INTEGER NOT NULL
);
COMMIT;
